default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 }.to_i %>
  timeout: 5000
  host: localhost
  port: 5433
  username: shadowrun_timeline
  password: shadowrun_timeline

development:
  <<: *default
  database: shadowrun_timeline_development

test:
  <<: *default
  database: shadowrun_timeline_test

production:
  pool: 15
