default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %
  username: shadowrun_timeline
  password: shadowrun_timeline
  host: localhost
  port: 5432

development:
  <<: *default
  database: shadowrun_timeline_development
  port: 5433

test:
  <<: *default
  database: shadowrun_timeline_test
  port: 5433

production:
  host: ENV['DATABASE_URL']
  pool: 15
  encoding: utf8
