name: Tests

on: [pull_request]
env:
  POSTGRES_PASSWORD: shadowrun_timeline
  POSTGRES_USER: shadowrun_timeline
  POSTGRES_HOST: localhost
  RAILS_ENV: test

jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: shadowrun_timeline
          POSTGRES_PASSWORD: shadowrun_timeline
        ports:
        - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby version (using project .ruby-version)
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Build webpack
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install JS dependencies
        run: yarn install

      - name: Create database
        run: bundler exec rails db:create db:migrate

      - name: Run tests
        run: bundle exec rspec
