name: Tests
on: push
env:
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
  POSTGRES_PASSWORD: shadowrun_timeline
  POSTGRES_USER: shadowrun_timeline
  POSTGRES_HOST: localhost

jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
        - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:latest
        ports:
        - 6379:6379
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby version (using project .ruby-version)
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Build webpack
        run: yarn install

      - name: Create database
        run: bundler exec rails db:create db:migrate

      - name: Run tests
        run: bundle exec rspec
